AllCops:
  NewCops: enable

# Unavailable on MRuby
Style/FrozenStringLiteralComment:
  Enabled: false

# module_function is no-op on MRuby
Style/ModuleFunction:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 70

Metrics/ModuleLength:
  Enabled: true
  Max: 100

Naming/MethodParameterName:
  Enabled: false
